[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
interface = ["dep:cw-orch"]

[dependencies]
cw-orch = {version = "0.18.1", optional = true }

warp-controller = { path = "../../contracts/warp-controller", default-features = false, version = "*", features = ["interface"]}
warp-funding-account = { path = "../../contracts/warp-funding-account", default-features = false, version = "*", features = ["interface"]}
warp-job-account = { path = "../../contracts/warp-job-account", default-features = false, version = "*", features = ["interface"] }
warp-job-account-tracker = { path = "../../contracts/warp-job-account-tracker", default-features = false, version = "*", features = ["interface"] }
warp-legacy-account = { path = "../../contracts/warp-legacy-account", default-features = false, version = "*", features = ["interface"] }
warp-resolver = { path = "../../contracts/warp-resolver", default-features = false, version = "*", features = ["interface"] }
warp-templates = { path = "../../contracts/warp-templates", default-features = false, version = "*", features = ["interface"] }

controller = { path = "../controller", default-features = false, version = "*", features = ["interface"] }
funding-account = { path = "../funding-account", default-features = false, version = "*", features = ["interface"] }
job-account = { path = "../job-account", default-features = false, version = "*", features = ["interface"] }
job-account-tracker = { path = "../job-account-tracker", default-features = false, version = "*", features = ["interface"] }
legacy-account = { path = "../legacy-account", default-features = false, version = "*", features = ["interface"] }
resolver = { path = "../resolver", default-features = false, version = "*", features = ["interface"] }
templates = { path = "../templates", default-features = false, version = "*", features = ["interface"] }