[package]
name = "account-tracker"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"

[dev-dependencies]
cw-multi-test = "0.16"
