[package]
name = "warp-templates-pkg"
version = "0.1.0"
authors = ["Terra Money <core@terra.money>"]
edition = "2021"

[features]
interface = ["dep:cw-orch"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-storage = "1.1"
cosmwasm-schema = "1.1"
cw-asset = "2.2"
cw20 = "0.16"
cw-storage-plus = "0.16"
cw2 = "0.16"
schemars = "0.8"
serde = { version = "1", default-features = false, features = ["derive"] }
warp-resolver-pkg = { path = "../resolver", default-features = false, version = "0.1.0" }
json-codec-wasm = "0.1.0"
strum = "0.24"
strum_macros = "0.24"
thiserror = { version = "1" }
warp-controller-pkg = {path = "../controller", version = "0.1.0"}
cw-orch = { version = "0.16.4", optional = true }

[dev-dependencies]
cw-multi-test = "0.16"
